name: device_orientation_windows
description: A Flutter plugin to get Windows device orientation using wingdi
version: 0.0.1
homepage: https://github.com/DeepHow/App-DeviceOrientationWindows

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DeviceOrientationWindowsPluginCApi
